[#ftl/]
${text!'textEmpty'}
${disabled!'disabledEmpty'}
${hidden!'hiddenEmpty'}
${radio!'radioEmpty'}
${checkbox!'checkboxEmpty'}
${select!'selectEmpty'}
${textarea!'textareaEmpty'}
${noName!'noNameEmpty'}
