[#ftl/]
[#macro class attributes name input]
[#if attributes['class']??]${attributes['class']}-${name} ${attributes['class']}-[#if input]input[#else]button[/#if] ${attributes['class']}-control [/#if]${name} [#if input]input[#else]button[/#if] control[#t/]
[/#macro]
[#macro append_attributes attributes list]
[#list attributes?keys as key][#t/]
[#if !list?seq_contains(key)][#t/]
 ${key?html}="${attributes(key)?string?html}"[#rt/]
[/#if][#t/]
[/#list][#t/]
[/#macro]